const num1 = 31;
const num2 = 2;
const num3 = 16;
const num4 = 6;
const num5 = 20;
const multiply = num1 * num2;
const random = Math.ceil(Math.random() * 1);
const mod = num3 % num4;
const max = Math.max(num4, num5);